export const endPoint = {
    login: '/login',
    register: '/register',
    registerGoogle: '/register/google',
    checkToken: '/check-token',
    logout: '/logout',
    allUsers: '/users/',
    searchUsers: '/users/search-users',
    oneUser: '/users/one-user/',
    deleteUser: '/users/delete-user',
    updateProfilePhoto: '/users/update-profile',
    allMessages: '/messages',
    sendMessage: 'messages/send-message',
    editMessage: '/messages/edit-message/',
    deleteMessage: '/messages/delete-message/',
}